name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
         sudo update-alternatives --remove-all gcc 
         sudo update-alternatives --remove-all g++

      shell: bash

    - name: Run tests
      run: chmod +x ./scripts/compile.sh && cd scripts && ./compile.sh tests && ../app/app-tests
