name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 

    - run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
         sudo update-alternatives --install /usr/bin/gcc gcc "/usr/bin/gcc-10"
         sudo update-alternatives --install /usr/bin/g++ g++ "/usr/bin/g++-10"
         sudo update-alternatives --set gcc "/usr/bin/gcc-10"
         sudo update-alternatives --set g++ "/usr/bin/g++-10"

      shell: bash

    - name: Run tests
      run: chmod +x ./scripts/compile.sh && cd scripts && ./compile.sh tests && ../app/app-tests
